name: ci

on:
  push:
    branches:
      - "master"


jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GROUP: weaveworksdemos
      COMMIT: ${{ github.sha }}
      REPO: shipping
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        run: mvn -B -DskipTests package --file pom.xml

      - name: Unit Tests
        run: mvn -q test

      - name: Integration Tests
        run: mvn integration-test

      - name: get short-sha
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      # Push to dockerhub
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: target/
          file: docker/shipping/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USER }}/${{ env.REPO }}:${{ steps.vars.outputs.sha_short }}
            ${{ secrets.DOCKER_USER }}/${{ env.REPO }}:latest
